# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'VS2017-Win2016'

variables:
  buildConfiguration: 'Release'

steps:
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'FinanceUtilities.Web'
- task: CmdLine@2
  inputs:
    script: |
      npm install -g @angular/cli
    workingDirectory: 'FinanceUtilities.Web'
- task: CmdLine@2
  inputs:
    script: |
      ng build --prod
    workingDirectory: 'FinanceUtilities.Web'
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.2.402'
- script: dotnet restore
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'FinanceUtilities.Api/FinanceUtilities.Api.csproj'
    zipAfterPublish: false
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\FinanceUtilities.Api\bin\Debug\netcoreapp2.2\publish'
    contents:  '**.*'
    targetFolder: $(Build.ArtifactStagingDirectory)
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'